baseurl = "https://www.laylab.me/"
title = "LB"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Layla Bouzoubaa"
    description = "LB's personal website"
    keywords = "blog,data science,personal,R, public health"
    info = "Data Science Wanderer"
    avatarurl = "images/lb.png"
    #gravatar = "john.doe@example.com"
    footercontent = "Dynamite with a laser beam"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
    #siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    #serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/labouz/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/bouzoulay/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/layla-bouzoubaa/"


[menu]
  
  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 1
  url = "/about/"

  [[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/posts/"

  #[[menu.main]]
  #name = "Now"
  #weight = 3
  #url = "now/"
  
  [[menu.main]]
  name = "Passion Projects/Talks"
  weight = 4
  url = "projects/"

  [[menu.main]]
  name = "Resume"
  weight = 5
  url = "/files/LB_20secs.pdf"
 

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

